// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:puptask/utils/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DaysAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(ThemeTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DaysAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(ThemeTypeAdapter());
  }
}
