// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQLG0N0mz5IUJsYIlmNAzCSVNJnuw4tY',
    appId: '1:861724315726:android:0f43b3244a04166524731f',
    messagingSenderId: '861724315726',
    projectId: 'puptask',
    storageBucket: 'puptask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDC11mt8AP2uAeqoonfp_Ht9NNAs9QXOQ',
    appId: '1:861724315726:ios:77d8abf45ea50ca824731f',
    messagingSenderId: '861724315726',
    projectId: 'puptask',
    storageBucket: 'puptask.firebasestorage.app',
    iosBundleId: 'com.CrashTestDummy.puptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDC11mt8AP2uAeqoonfp_Ht9NNAs9QXOQ',
    appId: '1:861724315726:ios:92353dac3dddb6e224731f',
    messagingSenderId: '861724315726',
    projectId: 'puptask',
    storageBucket: 'puptask.firebasestorage.app',
    iosBundleId: 'com.crashtestdummy.puptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcuOsM4rFtSm1XSIu5p3QvzVfAUqQ4lpo',
    appId: '1:861724315726:web:edcd20911cf64a9824731f',
    messagingSenderId: '861724315726',
    projectId: 'puptask',
    authDomain: 'puptask.firebaseapp.com',
    storageBucket: 'puptask.firebasestorage.app',
  );

}